version: '3.8'
services:
  api-service:
    build: ./api-service
    ports:
      - "9080:8080"  # ← Maps container 8080 to host 9080
    environment:
      - FLAKY_SERVICE_URL=http://flaky-service:8081
    depends_on:
      - flaky-service

  flaky-service:
    build: ./flaky-service
    ports:
      - "9081:8081"  # ← Different port to avoid conflict